rescue_mission/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"

  resources :questions do
    resources :answers, only: [:new, :create]
  end

  resources :answers, only: [:index, :update, :edit, :destroy]
end

rescue_mission/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :answer_description, presence: true, length: { minimum: 50 }
end

rescue_mission/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rescue_mission/app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, :dependent => :destroy

  validates :title, presence: true, length: { minimum: 40 }
  validates :description, presence: true, length: { minimum: 150 }
end

rescue_mission/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end


  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question

# @question.answers.new(answer_params)

    if @answer.save
      flash[:notice] = 'Answer was successfully created.'
    else
      flash[:notice] = "Failed to save answer."
    end
    redirect_to question_path @question
  end

  private

  def answer_params
    params.require(:answer).permit(:answer_description)
# .merge(question: Question.find(answer_params))
  end
end

rescue_mission/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rescue_mission/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  def edit
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit, notice:
      'Question not updated.'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end


end

rescue_mission/app/helpers/application_helper.rb
module ApplicationHelper
end

rescue_mission/app/views/answers/_answer_form.html.erb
<%= form_for [@question, @answer] do |f| %>

<% if @answer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

    <ul>
    <% @answer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= f.label :answer_description %>
    <%= f.text_field :answer_description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

rescue_mission/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rescue_mission/app/views/questions/_question_form.html.erb
<%= form_for(@question) do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this @question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

rescue_mission/app/views/questions/edit.html.erb
<h1> Edit Question </h1>

<%= render 'question_form', question: @question %>
<%= link_to 'Back', questions_path %>

rescue_mission/app/views/questions/index.html.erb
<h1> Questions</h1>

<ul>
  <% @questions.each do |question| %>
  <li> <%= link_to question.title, question %> </li>
  <% end %>
</ul>


<%= link_to 'New Question', new_question_path %>

rescue_mission/app/views/questions/new.html.erb
<h1> New Question </h1>

<%= render 'question_form', question: @question %>
<%= link_to 'Back', questions_path %>

rescue_mission/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_question_path %>
<%= link_to 'Delete', question_path(@question), :method => "delete", data: {confirm: "Are you sure?"} %>
<%= link_to 'Back', questions_path %>

<h3>Question Title:</h3>
<p><%= @question.title %></p>

<h3>Question Description:</h3>
<p><%= @question.description %></p>

<h3>Answers:</h3>

<ul>
  <% @question.answers.each do |answer| %>
  <li> <%= answer.answer_description%> </li>
  <% end %>
</ul>

<%= render :partial => '/answers/answer_form', answer: @answer%>